---
title: Data Analysis with R Programming - How a Bikeshare Company Navigates Its Speedy Success
author: "Ryan Nguyen"
output: html_document
fig_caption: yes
theme: cerulean
toc: yes
toc_depth: 3
toc_float: yes
---

## Scenario:

Imagine being a junior data analyst in the marketing team at Divvy bike share
company in Chicago and working on a project to increase the company's profit by increasing the numbers of riders with annual membership. Your team must know the differences between casual riders and annual members to come up and put forward the marketing strategies for the executives' approval. 


## Clear Statement of Business Task (ASK)

The purpose of this project is to understand the differences between Divvy casual riders and annual members to help design an effective marketing program targeting and converting casual riders into members. 

## A description of all the data sources used (PREPARE)

Rides data is collected and publicly published monthly by Divvy themselves to let people analyze and make the data speak meaningful insights. 

* Reliable: This data is the first-party data so YES.
* Organized: The observation's attributes are well-organized and include: Ride ID, user type, start time, end time, bike type, start station name, start station id, end station name, end station id, start longitude, start latitude, end latitude, end longitude, 
* Cited: Data is provided under the company data [License Agreement](https://ride.divvybikes.com/data-license-agreement)
* Comprehensive: The data set is large enough and has relevant attributes to conduct meaningful analysis.
* Current: They are updated every month and stored on their server. This data set includes data from September 2020 to August 2021.



View this analysis on my Tableau Dashboard [here](https://public.tableau.com/views/Book1_16409358660030/Dashboard1?:language=en-US&:display_count=n&:origin=viz_share_link)